  apache_ciphers: '-ALL:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA'
  idpconf_shibboleth_version: 'shibboleth-identity-provider-3.4.6'
  idpconf_core_sp_metadata_url: 'https://{{ int_router_host }}:{{ int_router_port }}/static/metadata/sp-metadata.xml'
  idpconf_host: '{{ ext_router_host }}'
  idpconf_scope: '{{ ext_router_host }}'
  idpconf_logo_height: '70'
  idpconf_logo_width: '229'
  idpconf_organisation_url: 'http://vm.fi/palveluarkkitehtuuri'
  idpconf_organisation_url_fi: 'http://vm.fi/palveluarkkitehtuuri'
  idpconf_organisation_url_en: 'http://vm.fi/palveluarkkitehtuuri'
  idpconf_organisation_url_sv: 'http://vm.fi/palveluarkkitehtuuri'
  idpconf_idp_shibboleth_error_tag: 'testidpshib'
  idpconf_idp_tomcat_error_tag: 'testidptc'
  idpconf_binding_path: 'testidp'
