  release_version: 'v8.1.0'
  sp_port: '8030'
  sp_target_port: '443'
  sp_ports: '-p {{ sp_port }}:{{ sp_target_port }}'
  sp_container_name: 'service-provider-container'
  sp_directory: 'sp'
  sp_mounts: '-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z'
  idp_port: '8031'
  idp_target_port: '8443'
  idp_ports: '-p {{ idp_port }}:{{ idp_target_port }}'
  idp_container_name: 'identity-provider-container'
  idp_directory: 'idp'
  proxy_port: '8032'
  proxy_target_port: '8443'
  proxy_ports: '-p {{ proxy_port }}:{{ proxy_target_port }}'
  proxy_container_name: 'proxy-server-container'
  proxy_directory: 'proxy'
  metadata_ports: '-p {{ metadata_port }}:8443'
  metadata_conf_directory: 'metadata'
  metadata_mounts: '-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z'
  tupas_idp_port: '8034'
  tupas_idp_target_port: '8443'
  tupas_idp_ports: '-p {{ tupas_idp_port }}:{{ tupas_idp_target_port }}'
  tupas_idp_container_name: 'integration-identity-provider-container'
  tupas_idp_directory: 'tupasidp'
  tupas_idp_mounts: '-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z'
  hst_idp_port: '8038'
  hst_idp_target_port: '8443'
  hst_idp_ports: '-p {{ hst_idp_port }}:{{ hst_idp_target_port }}'
  hst_container_name: 'hst-identity-provider-container'
  hst_directory: 'hst-idp'
  vtj_port: '8035'
  vtj_port2: '8044'
  vtj_ports2: '-p {{ vtj_port2 }}:{{ vtj_target_port }}'
  vtj_container_name: 'vtj-client-container'
  vtj_container_name2: 'vtj-client-container2'
  vtj_directory: 'vtj'
  vtj_directory2: 'vtj2'
  vtj_mounts: '-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z'
  static_port: '8036'
  static_ports: '-p {{ static_port }}:443'
  static_directory: 'static'
  static_container_name: 'e-identification-static-container'
  localisation_port: '8070'
  localisation_ports: '-p {{ localisation_port }}:443'
  localisation_mounts: '-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z'
  localisation_directory: 'localisation'
  int_router_port: '8037'
  int_router_ports: '-p {{ int_router_port }}:443'
  int_router_mounts: '-v {{ deploydir }}/nginx:/etc/nginx/conf.d:z -v {{ deploydir }}/ssl:/etc/nginx/ssl:z -v {{ logdir }}:/var/log/nginx:z'
  int_router_directory: 'internal-router'
  int_router_container_name: 'e-identification-internal-router-container'
  ext_router_port: '443'
  ext_router_directory: 'external-router'
  ext_router_container_name: 'e-identification-external-router-container'
  hst_router_target_port: '443'
  hst_router_mounts: '   -v {{ deploydir }}/html:/html:z -v {{ deploydir }}/certcheck:/certcheck:z -v {{ deploydir }}/apache/conf/apache-hst.conf:/usr/local/apache2/conf/apache-hst.conf:z -v {{ deploydir }}/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:z -v {{ hst_router_host_cert_path }}:/etc/apache/ssl:z -v {{ logdir }}:/data00/logs:z'
  hst_router_directory: 'hst-router'
  hst_router_container_name: 'e-identification-hst-router-container'
  eidas_router_directory: "eidas-router"
  eidas_router_mounts: " -v {{ deploydir }}/apache/conf/apache-site.conf:/usr/local/apache2/conf/apache-site.conf:z -v {{ deploydir }}/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:z -v {{ eidas_router_host_cert_path }}:/etc/apache/ssl:z -v {{ logdir }}:/data00/logs:z "
  eidas_router_container_name: 'e-identification-eidas-router-container'
  feedback_port: '8039'
  feedback_target_port: '8443'
  feedback_ports: '-p {{ feedback_port }}:{{ feedback_target_port }}'
  feedback_container_name: 'e-identification-feedback-container'
  feedback_directory: 'feedback'
  feedback_mounts: '-v {{ deploydir }}/config:/data00/deploy/config:z -v {{ deploydir }}/ssl:/data00/deploy/ssl:z -v {{ logdir }}:/data00/logs:z'
  test_idp_port: '8099'
  test_idp_target_port: '8443'
  test_idp_ports: '-p {{ test_idp_port }}:{{ test_idp_target_port }}'
  test_idp_container_name: 'test-idp-container'
  test_idp_directory: 'test-idp'
  vartti_port: '8047'
  vartti_target_port: '8443'
  vartti_ports: ' -p {{ vartti_port }}:{{ vartti_target_port }}'
  vartti_container_name: 'vartti-client-container'
  vartti_directory: 'vartti'
  vartti_mounts: '-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z'
  eidas_port: '8052'
  eidas_target_port: '8888'
  eidas_ports: ' -p {{ eidas_port }}:{{ eidas_target_port }}'
  eidas_container_name: 'e-identification-eidas-node-container'
  eidas_directory: "eidas"
  eidas_mounts: "-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z"
  default_error_url: 'https://{{ ext_router_host }}/500/'
  discovery_page_path: 'https://{{ ext_router_host }}/sivut/discovery-page/'
  nginx_ciphers: '-ALL:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA'
  tomcat_threads: '500'
  proxy_rest_url: 'https://{{ int_router_host }}:{{ int_router_port }}/proxy'
  jdbc_db_url: 'jdbc:postgresql://{{ metadata_postgres_host }}:{{ metadata_postgres_port }}/metadata'
  shibgen_outputpath: 'certs'
  spconf_location_eidas_base: "/LoginEIDAS1"
