---
  sp_host: 'tun-pub-adap1'
  sp_imagename: "service-provider:local"
  testsp_host: 'tun-pub-router1'
  testsp_port: '443'
  testsp_ports: '-p 192.168.0.3:{{ testsp_port }}:443'
  testsp_mounts: "-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z -v {{ testsp_host_cert_path }}:/etc/ssl/certs:z"
  testsp_directory: "test-service"
  testsp_imagename: "e-identification-test-service:local"
  testsp_container_name: 'test-service-container'
  idp_host: 'tun-pub-idp1'
  idp_imagename: "identity-provider:local"
  idp_mounts: "-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z"
  proxy_host: 'tun-pub-beprx1'
  proxy_imagename: "proxy-server:local"
  proxy_mounts: "-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z"
  metadata_host: 'tun-pub-beprx1'
  metadata_port: '8033'
  metadata_postgres_host: 'tun-pub-beprx1'
  metadata_postgres_port: '5432'
  metadata_container_name: 'metadata-server-container'
  metadata_imagename: "metadata-server:local"
  metadata_db_imagename: "postgres"
  metadata_directory: "metadata"
  metadata_db_container_name: 'metadata-postgres'
  metadata_db_directory: "metadata"
  tupas_idp_host: 'tun-pub-adap1'
  tupas_idp_imagename: "e-identification-tupas-idp:local"
  hst_idp_host: 'tun-pub-adap1'
  hst_imagename: "e-identification-hst-idp:local"
  hst_idp_mounts: "-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z -v {{ host_crl_dir_path }}:{{ crl_dir_path }}:z -v {{ host_ica_dir_path }}:{{ ica_dir_path }}:z -v {{ host_ca_dir_path }}:{{ ca_dir_path}}:z"
  vtj_host: 'tun-pub-beprx1'
  vtj_host2: 'tun-pub-cache1'
  vtj_target_port: '8035'
  vtj_ports: '  -p {{ vtj_port }}:{{ vtj_target_port }}'
  vtj_imagename: "e-identification-vtj-client:local"
  static_host: 'tun-pub-cache1'
  static_mounts: "-v {{ deploydir }}:/data00/deploy:z -v {{ deploydir }}/nginx:/etc/nginx/conf.d:z -v {{ deploydir }}/ssl:/etc/nginx/ssl:z -v {{ deploydir }}/metadata:/usr/share/nginx/html/metadata:z -v {{ logdir }}:/var/log/nginx:z -v {{ deploydir }}/git-info:/usr/share/nginx/html/version.txt:z -v {{ deploydir }}/disruption_message.json:/usr/share/nginx/html/resources/js/disruption_data/disruption_message.json:z"
  static_imagename: "e-identification-static:local"
  localisation_host: 'tun-pub-cache1'
  localisation_imagename: "e-identification-localisation-service:local"
  localisation_container_name: 'e-identification-localisation-service-container'  
  int_router_host: 'tun-pub-cache1'
  int_router_imagename: "e-identification-internal-router:local"
  ext_router_host: 'tunnistaminen.test'
  ext_router_internal_host: 'tun-pub-router1'
  ext_router_ports: '-p 192.168.0.1:{{ ext_router_port }}:443 -p 192.168.0.1:80:80'
  ext_router_mounts: "-v {{ deploydir }}/nginx/nginx.conf:/etc/nginx/nginx.conf:z -v {{ deploydir }}/nginx/conf.d:/etc/nginx/conf.d:z -v {{ external_router_host_cert_path }}:/etc/nginx/ssl:z -v {{ deploydir }}/html:/etc/nginx/html:z -v {{ logdir }}:/var/log/nginx:z -v {{ deploydir }}/nginx_cache:/nginx_cache:Z"
  ext_router_imagename: "e-identification-external-router:local"
  ext_router_sp_metadata_config: 'allow 0.0.0.0/0;'
  hst_router_host: 'kortti.tunnistaminen.test'
  hst_router_port: '443'
  hst_router_ports: '-p 192.168.0.2:{{ hst_router_port }}:{{ hst_router_target_port }}'
  hst_router_imagename: "e-identification-hst-router:local"
  eidas_router_host: 'tun-pub-metadata1'
  eidas_router_port: '8051'
  eidas_router_target_port: '443'
  eidas_router_ports: '-p 192.168.0.5:{{ eidas_router_port }}:{{ eidas_router_target_port }}'
  eidas_router_imagename: "e-identification-eidas-router:local"
  feedback_host: 'tun-pub-cache1'
  feedback_imagename: "e-identification-feedback:local"
  fake_vtj_host: 'tun-pub-beprx1'
  fake_vtj_port: '8041'
  fake_vtj_port2: '8043'
  fake_vtj_controller_port: '8046'
  fake_vtj_ports: '  -p {{ fake_vtj_port }}:8080 -p {{ fake_vtj_port2 }}:8081 -p {{ fake_vtj_controller_port }}:8082'
  fake_vtj_container_name: 'fake-vtj-container'
  fake_vtj_imagename: "e-identification-fake-vtj:local"
  fake_vtj_directory: "fake-vtj"
  fake_vtj_mounts: "-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z -v /var/run/docker.sock:/var/run/docker.sock:z -v {{ deploy_root }}/logs:/tmp/logs:z"
  test_idp_host: 'tun-pub-adap1'
  test_idp_imagename: "e-identification-test-idp:local"
  test_idp_mounts: "-v {{ deploydir }}:/data00/deploy:z -v {{ logdir }}:/data00/logs:z"
  vartti_host: 'tun-pub-beprx1'
  vartti_imagename: "e-identification-vartti-client:local"
  eidas_host: 'tun-pub-beprx1'
  eidas_imagename: "e-identification-eidas-node:local"
#
  env: "local"
  log_level: "DEBUG"
  docker_registry: "e-identification-docker-virtual.vrk-artifactory-01.eden.csc.fi"
  additional_docker_configs: " --add-host tunnistaminen.test:192.168.0.1 --add-host kortti.tunnistaminen.test:192.168.0.2 --add-host {{ sp_host }}:192.168.0.1 --add-host {{ idp_host }}:192.168.0.1 --add-host {{ proxy_host }}:192.168.0.1 --add-host {{ metadata_host }}:192.168.0.1 --add-host {{ tupas_idp_host }}:192.168.0.1 --add-host {{ proxy_host }}:192.168.0.1 --add-host {{ int_router_host }}:192.168.0.1 --add-host {{ int_router_host }}:192.168.0.1 {{ '--add-host ' ~ vartti_api_host ~ ':192.168.0.4' if vartti_api_host is defined else ''}}"
  java_xmx_megabytes: "1024"
  tomcat_ciphers: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA"
  phase_id_time_interval: '300'
  phase_id_time_interval_auth: '600'
  phase_id_time_built_interval: '10'
  apro_ca_cert: "kapa-ca-pub-cert.pem"
  apro_ssl_key: "ssl.key"
  apro_ssl_cert: "ssl.crt"
  shibgen_core_idp_id: "pub_core_idp"
  shibgen_core_sp_id: "pub_core_sp"
